identity =input('你的身分是:1.老師 2.學生')
if(identity==1)
    id = input('NID：')
    name = input('姓名:')
    department = input('系所:')
    sex = input('性別:')
    residence = input('居住地:')
else if(identity==2)
    id = input('NID：')
    name = input('姓名:')
    department = input('系所:')
    grade = input('年級:')
    sex = input('性別:')
    residence = input('居住地:')